Docs/component interaction
paastech-cloud/docs pull request #7
Opened 2023-07-09 09:56 UTC by thomas-mauran

2023-07-11 20:53 UTC, BioTheWolff submitted a review, later dismissed
LGTM!

2023-07-12 13:51 UTC, Kuruyia requested changes

2023-07-12 13:51 UTC, Kuruyia commented on Architecture.md
> +In this schema we can see many different component interacting with each other. We decided for this first iteration to split services as much as we could to allow for a more modular architecture. Thi
```suggestion
In this schema, we can see the different components interacting with each other. We decided, for this first iteration, to split services as much as we could to allow for a more modular architecture. This allows us to easily replace a component if needed, and to scale the different components independently.
```

2023-07-12 13:51 UTC, Kuruyia commented on Architecture.md
> +- The client API is the main component that will be used by the clients to interact with the service. This API will then interact with the git controller to create repositories and with pomegranate t
```suggestion
- The client API is the main component that will be used by the clients to interact with the service. This API will then interact with the Git controller to create repositories and with Pomegranate to create Docker deployments, and with the database to store the data.
```

2023-07-12 13:51 UTC, Kuruyia commented on Architecture.md
> +- The git controller will interact with the host filesystem to create repositories, and with the local container registry to push images.
```suggestion
- The Git controller will interact with the host file system to create repositories, and with the local container registry to push images.
```

2023-07-12 13:51 UTC, Kuruyia commented on Architecture.md
> +- Pomegranate, our deployment manager, will interact with the local container registry to pull images and with the host filesystem to create deployments.
```suggestion
- Pomegranate, our deployment manager, will interact with the local container registry to pull images and with the host file system to create deployments.
```

2023-07-12 13:51 UTC, Kuruyia commented on Architecture.md
> +Most of the interactions between the different components are done through gRPC, except for the web frontend and the CLI, which use HTTP requests. Using gRPC allows for a more efficient communication
```suggestion
Most of the interactions between the different components are done through gRPC, except for the web frontend and the CLI, which use HTTP requests. Using gRPC allows for a more efficient communication between the components, as well as a more secure one, as the communication is done through a private network. While the HTTP requests allows us easier access to the API.
```

2023-07-12 16:01 UTC, Mathias-Boulay requested changes
The idea is good, however a few suggestions:
- most sentences need to be straightforward. Go straight to the point.
- Using gRPC doesn't mean our communications are intrinsically secured.

2023-07-12 16:02 UTC, Mathias-Boulay commented
Also, I forgot to mention but the graph background colors aren't the best fit for the official gh dark theme. Perhaps use a desaturated palette ?

2023-07-12 18:45 UTC, Mathias-Boulay approved these changes
Nice :+1:

2023-07-12 19:00 UTC, BioTheWolff approved these changes
LGTM!

2023-07-12 19:05 UTC, Mathias-Boulay approved these changes
LGTM :+1:

2023-07-12 19:08 UTC, merged